
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const TODAY=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const parse=s=>{const [y,m,d]=s.split('-').map(Number);return new Date(Date.UTC(y,m-1,d))};
const iso=d=>d.toISOString().slice(0,10), dayms=86400000;
function plusMonths(s,n){const d=parse(s),end=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+n+1,0)).getUTCDate();return iso(new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+n,Math.min(d.getUTCDate(),end))))}
function ageAt(birth,today=TODAY()){const b=parse(birth),t=parse(today);let m=(t.getUTCFullYear()-b.getUTCFullYear())*12+t.getUTCMonth()-b.getUTCMonth();if(plusMonths(birth,m)>today)m--;return {months:m,days:Math.round((t-parse(plusMonths(birth,m)))/dayms),totalDays:Math.round((t-b)/dayms)}}
const pretty=s=>s.replaceAll('-','.');
const DEFAULT={version:1,profile:{name:'우리 아이',birth:'2025-01-01',sex:'boys'},measurements:[],observations:{},checks:{}};
let state=structuredClone(DEFAULT),storageOK=true;
try{const raw=localStorage.getItem('yuha-growth-v1');if(raw){const v=JSON.parse(raw);if(v.version===1&&v.profile&&Array.isArray(v.measurements)&&v.observations&&v.checks)state=v}}catch{storageOK=false}
function save(){if(window.cloudAvailable&&cloud.user){cloudChanged();return true}try{localStorage.setItem('yuha-growth-v1',JSON.stringify(state));storageOK=true;$('#storageNote').textContent='◌ 이 브라우저에 저장 중 · 온라인 동기화 전';return true}catch{storageOK=false;$('#storageNote').textContent='저장 공간을 사용할 수 없어요 · 기록을 내려받아 보관하세요';toast('브라우저 저장 실패 · 현재 화면에만 보관 중');return false}}
function toast(s){$('#toast').textContent=s;$('#toast').classList.remove('hidden');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').classList.add('hidden'),3200)}
const SRC={who:'https://www.who.int/tools/child-growth-standards/standards/motor-development-milestones',cdc:'https://www.cdc.gov/act-early/milestones/',nip:'https://nip.kdca.go.kr/irhp/infm/goVcntInfo.do?menuCd=115&menuLv=1',check:'https://www.mohw.go.kr/menu.es?mid=a10706020200',growth:'https://www.who.int/tools/child-growth-standards'};
const skills=[
{id:'sit',group:'motor',label:'혼자 앉기',start:3.8,end:9.2,title:'도움 없이 앉아요',text:'손이나 보호자의 도움 없이 앉는 모습이에요. WHO 연구의 관찰 범위는 약 3.8~9.2개월입니다.',tip:'안전한 바닥에서 가까이 지켜보며 장난감을 함께 탐색해 보세요.',src:SRC.who},
{id:'standhelp',group:'motor',label:'잡고 서기',start:4.8,end:11.4,title:'도움을 받아 서요',text:'지지할 곳을 잡고 서는 대근육 발달을 살펴봐요. 연구에서 관찰된 범위는 약 4.8~11.4개월입니다.',tip:'넘어지지 않는 낮고 튼튼한 가구 주변을 정리하고 곁에서 지켜봐 주세요.',src:SRC.who},
{id:'crawl',group:'motor',label:'네 발 기기',start:5.2,end:13.5,title:'손과 무릎으로 기어요',text:'두 손과 무릎을 사용해 이동해요. 연구 관찰 범위는 약 5.2~13.5개월이며, 모든 아이가 같은 이동 단계를 거치는 것은 아닙니다.',tip:'손이 닿을 듯한 곳에 좋아하는 큰 장난감을 두고 스스로 이동해 보게 해 주세요.',src:SRC.who},
{id:'walkhelp',group:'motor',label:'잡고 걷기',start:6,end:13.7,title:'도움을 받아 걸어요',text:'가구나 보호자의 손을 잡고 발걸음을 옮기는 모습이에요. 연구 관찰 범위는 약 6.0~13.7개월입니다.',tip:'고정된 가구 주변의 날카로운 모서리와 미끄러운 물건부터 정리해 주세요.',src:SRC.who},
{id:'stand',group:'motor',label:'혼자 서기',start:6.9,end:16.9,title:'잠깐, 혼자 서 있어요',text:'지지 없이 서는 모습을 기록해 보세요. WHO 연구에서는 약 6.9~16.9개월에 걸쳐 관찰되었습니다.',tip:'자세를 억지로 유지시키기보다 아이가 스스로 시도할 때 가까이서 지켜봐 주세요.',src:SRC.who},
{id:'walk',group:'motor',label:'혼자 걷기',start:8.2,end:17.6,title:'혼자 발걸음을 옮겨요',text:'도움 없이 걷기까지의 시기는 폭넓습니다. 연구 관찰 범위는 약 8.2~17.6개월이며, 이 범위만으로 발달 상태를 판정하지 않아요.',tip:'안전하고 평평한 공간에서 아이가 자기 속도로 움직일 시간을 주세요.',src:SRC.who}
];
skills.push(...window.EXTRA_SKILLS);
const events=[
{id:'check1',group:'health',type:'검진',label:'첫 건강검진',start:14/30.4375,end:35/30.4375,dayStart:14,dayEnd:35,title:'1차 영유아 건강검진',text:'생후 14~35일에 받는 첫 검진입니다. 정확한 검진 가능 기간은 국민건강보험에서 확인하세요.',src:SRC.check},
{id:'vac2',group:'health',type:'접종',label:'2개월 접종',point:2,title:'2개월 예방접종 일정 확인',text:'기초 접종 시기입니다. 아기수첩과 예방접종도우미에서 백신별 일정·접종력을 확인하세요.',src:SRC.nip},
{id:'vac4',group:'health',type:'접종',label:'4개월 접종',point:4,title:'4개월 예방접종 일정 확인',text:'이전 접종력과 백신 종류를 확인해 의료기관과 다음 접종일을 정하세요.',src:SRC.nip},
{id:'check2',group:'health',type:'검진',label:'2차 건강검진',start:4,end:7,endMonth:6,title:'2차 영유아 건강검진',text:'생후 4~6개월 검진입니다. 문진·진찰·신체 계측과 시기별 건강교육을 받습니다.',src:SRC.check},
{id:'vac6',group:'health',type:'접종',label:'6개월 접종',point:6,title:'6개월 예방접종 일정 확인',text:'백신별 다음 접종과 인플루엔자 접종 대상 여부를 의료기관에 확인하세요. 제품과 접종력에 따라 일정이 달라집니다.',src:SRC.nip},
{id:'check3',group:'health',type:'검진',label:'3차 건강검진',start:9,end:13,endMonth:12,title:'3차 영유아 건강검진',text:'생후 9~12개월 검진입니다. 발달선별검사와 상담을 위해 평소 궁금했던 행동을 적어 가세요.',src:SRC.check},
{id:'mmr',group:'health',type:'접종',label:'MMR 1차',start:12,end:16,endMonth:15,title:'MMR 1차 접종',text:'표준 접종 시기는 생후 12~15개월입니다. 실제 접종 가능일은 아이의 이전 접종력과 상태를 확인해 의료기관에서 결정합니다.',src:'https://nip.kdca.go.kr/irhp/infm/goVcntInfo.do?menuCd=1107&menuLv=1'},
{id:'hib',group:'health',type:'접종',label:'Hib 추가접종',start:12,end:16,endMonth:15,title:'Hib 추가접종',text:'표준 추가접종 시기는 생후 12~15개월입니다. 이전 접종 횟수와 접종 시작 나이에 따라 일정이 달라질 수 있어요.',src:'https://www.kdca.go.kr/kdca/3342/subview.do'},
{id:'dtap',group:'health',type:'접종',label:'DTaP 4차',start:15,end:19,endMonth:18,title:'DTaP 4차 접종',text:'표준 접종 시기는 생후 15~18개월입니다. 이전 차수와의 간격을 의료기관에서 확인하세요.',src:'https://nip.kdca.go.kr/irhp/infm/goVcntInfo.do?menuCd=1103&menuLv=1'},
{id:'hepa',group:'health',type:'접종',label:'A형간염 1차',start:12,end:24,endMonth:23,title:'A형간염 1차 접종',text:'생후 12~23개월에 1차 접종을 권고합니다. 2차는 백신 종류에 따라 1차 후 6~12개월 또는 6~18개월 뒤에 접종합니다.',src:'https://nip.kdca.go.kr/irhp/infm/goVcntInfo.do?menuCd=1109&menuLv=1'},
{id:'check4',group:'health',type:'검진',label:'4차 건강검진',start:18,end:25,endMonth:24,title:'4차 영유아 건강검진',text:'생후 18~24개월 검진입니다. 발달선별검사와 신체 계측, 상담을 받습니다. 정확한 종료일은 국민건강보험에서 확인하세요.',src:SRC.check}
];
events.push(...[[30,37,36,'check5','5차 건강검진'],[42,49,48,'check6','6차 건강검진'],[18,30,29,'dental1','1차 구강검진'],[30,42,41,'dental2','2차 구강검진'],[42,54,53,'dental3','3차 구강검진']].map(([start,end,endMonth,id,title])=>({id,group:'health',type:'검진',label:title,start,end,endMonth,title,text:`생후 ${start}~${endMonth}개월 대상입니다. 정확한 개인별 검진 가능 기간은 국민건강보험에서 확인하세요.`,src:SRC.check})));
let unit='month',filter='all',selected='bye12',detailTab='feature',scheduleFilter='upcoming',selectedMonth=Math.min(48,Math.max(0,ageAt(state.profile.birth).months));
function current(){return ageAt(state.profile.birth)}
function monthPosition(m){return m}
function colWidth(){return parseFloat(getComputedStyle($('#boardInner')).getPropertyValue('--col'))}
function renderHeader(){const a=current();$('#childName').textContent=state.profile.name;$('#birthText').textContent=pretty(state.profile.birth)+' 출생';$('#ageText').textContent=a.months+'개월 '+a.days+'일';$('#todayText').textContent=pretty(TODAY())+' 기준';$('#todayBtn').textContent=state.profile.name+'의 지금';document.title=state.profile.name+'의 성장지도';if(!storageOK)$('#storageNote').textContent='브라우저 저장 불가 · 현재 화면에만 보관 중';renderMetrics()}
function percentile(r,key){const days=ageAt(state.profile.birth,r.date).totalDays,m=days/30.4375,sex=state.profile.sex||'boys';if(m<0||m>60||r[key]==null)return null;let val=Number(r[key]),type=key;if(key==='height'){if(!r.posture||r.posture==='unknown')return null;type=m<24?'length':'height';if(m<24&&r.posture==='standing')val+=.7;if(m>=24&&r.posture==='lying')val-=.7}const data=WHO_LMS[sex+'_'+type];if(!data)return null;const lo=data.filter(x=>x[0]<=m).at(-1)||data[0],hi=data.find(x=>x[0]>=m)||data.at(-1),f=hi[0]===lo[0]?0:(m-lo[0])/(hi[0]-lo[0]);const [L,M,S]=[1,2,3].map(k=>lo[k]+f*(hi[k]-lo[k]));const z=L===0?Math.log(val/M)/S:(Math.pow(val/M,L)-1)/(L*S);const t=1/(1+.2316419*Math.abs(z)),d=.3989422804014327*Math.exp(-z*z/2);let c=1-d*t*(.319381530+t*(-.356563782+t*(1.781477937+t*(-1.821255978+t*1.330274429))));if(z<0)c=1-c;return {p:c*100,z,ageDays:days,median:M}}
function percentileLabel(r,k){const v=percentile(r,k);if(!v)return k==='height'&&(!r.posture||r.posture==='unknown')?'자세 선택 후 백분위 표시':'기준 범위 밖';return 'WHO 약 '+(v.p<.1?'0.1 미만':v.p>99.9?'99.9 초과':v.p.toFixed(1))+'백분위'}
function renderMetrics(){const fields=[['height','키','cm','↕'],['weight','몸무게','kg','◴']];$('#metrics').innerHTML=fields.map(([key,label,u,icon])=>{const latest=[...state.measurements].filter(r=>r[key]!=null).sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id)[0];return `<button class="metric" data-metric="${key}"><span class="label">${icon} ${label}</span>${latest?`<b>${latest[key]}<span class="unit">${u}</span></b><small>${percentileLabel(latest,key)}</small><small>${pretty(latest.date)} 측정</small>`:`<b class="empty-value">+ 기록하기</b><small>기록하면 백분위를 보여줘요</small>`}</button>`}).join('');$$('[data-metric]').forEach(b=>b.onclick=()=>measurementForm(b.dataset.metric))}
function rangeLabel(i){if(i.point!=null)return `${i.point}개월 확인`;if(i.dayStart)return '생후 14~35일';return `${i.start}~${i.endMonth??Math.min(48,i.end)}개월${i.end>48?' 이후도':''}${i.kind==='guide'?' · 안내':''}`}
function renderBoard(){const age=current(),groups={motor:'몸과 움직임',cognitive:'인지와 소통',food:'식사와 영양',life:'수면과 배변',teeth:'치아와 양치',supplies:'기저귀·분유 단계',health:'접종과 검진'};$('#boardInner').style.setProperty('--current-left',`calc(${Math.min(48,Math.max(0,age.months))} * var(--col))`);const head=`<div class="timehead"><div class="corner">${unit==='month'?'월령 (개월)':'생후 주수'}</div><div class="months">${Array.from({length:49},(_,m)=>{const week=Math.floor((parse(plusMonths(state.profile.birth,m))-parse(state.profile.birth))/dayms/7);return `<button class="month ${m===age.months?'current':''} ${m===selectedMonth?'picked':''}" data-month="${m}"><small>${m===age.months?'지금':unit==='week'?m+'개월':''}</small>${unit==='month'?m:week+'주'}</button>`}).join('')}</div></div>`;let rows='';for(const [g,name] of Object.entries(groups)){if(filter!=='all'&&filter!==g)continue;rows+=`<div class="group-heading ${g}" data-group="${g}"><span>${name}</span></div>`;for(const i of [...skills,...events].filter(x=>x.group===g)){const isPoint=i.point!=null,seen=g==='health'?state.checks[i.id]:state.observations[i.id];const attrs=`data-item="${i.id}" aria-label="${escapeHTML(i.title+' · '+rangeLabel(i))}"`;const observation=i.kind==='cdc'?`<button class="range ${g} observe" style="left:calc(${i.observeStart} * var(--col));width:calc(${i.point+.5-i.observeStart} * var(--col))" ${attrs}><span>관찰해요</span></button>`:'';rows+=`<div class="row ${g}" data-row="${i.id}" data-row-group="${g}"><button class="row-label" ${attrs}><span>${escapeHTML(i.label)}${seen?' ✓':''}<small>${rangeLabel(i)}</small></span></button><div class="track">${observation}${isPoint?`<button class="point ${g} ${selected===i.id?'selected':''}" style="left:calc((${i.point} + .5) * var(--col))" ${attrs}><span>${seen?'✓':'·'}</span></button>`:`<button class="range ${g} ${selected===i.id?'selected':''} ${seen?'checked':''} ${i.kind==='guide'?'guide-range':''}" style="left:calc(${i.start} * var(--col));width:calc(${Math.min(49,i.end)-i.start} * var(--col))" ${attrs}><span>${escapeHTML(i.label)}</span></button>`}</div></div>`}}$('#boardInner').innerHTML=head+rows;$$('[data-item]').forEach(b=>b.onclick=()=>selectItem(b.dataset.item));$$('[data-month]').forEach(b=>b.onclick=()=>{selectedMonth=+b.dataset.month;renderBoard();renderBelow()});updatePeriod(false)}
function goToday(){selectedMonth=Math.min(48,Math.max(0,current().months));renderBoard();renderBelow();$('#board').scrollTo({left:Math.max(0,(selectedMonth-1)*colWidth()),behavior:'smooth'})}
function updatePeriod(syncSelection=true){const oldMonth=selectedMonth;const board=$('#board'),cw=colWidth(),label=parseFloat(getComputedStyle($('#boardInner')).getPropertyValue('--label')),left=board.scrollLeft/cw,right=Math.min(49,left+(board.clientWidth-label)/cw);const first=Math.floor(left),last=Math.min(48,Math.ceil(right)-1);$('#period').textContent=`${first}~${last}개월`;const visibleGroups=new Set();for(const row of $$('[data-row]')){const i=[...skills,...events].find(i=>i.id===row.dataset.row);const start=i.observeStart??i.start??i.point,end=i.end??(i.point+1);const visible=end>left&&start<right;row.hidden=!visible;if(visible)visibleGroups.add(i.group)}$$('[data-group]').forEach(e=>e.hidden=!visibleGroups.has(e.dataset.group));if(syncSelection!==false){selectedMonth=Math.max(0,Math.min(48,first));if(oldMonth!==selectedMonth)renderBelow()}}
function selectItem(id){selected=id;detailTab='feature';renderBoard();renderDetail();if(innerWidth<761)$('#detail').scrollIntoView({behavior:'smooth',block:'start'})}
function renderDetail(){const i=[...skills,...events].find(x=>x.id===selected),isHealth=i.group==='health';$('#detail').innerHTML=`<div class="detail-head"><div class="detail-symbol">${isHealth?'♡':i.group==='motor'?'↟':'☏'}</div><div><h3>${escapeHTML(i.title)}</h3><div class="detail-sub">${rangeLabel(i)} · ${isHealth?i.type:i.group==='supplies'?'사용·전환 가이드':i.group==='motor'?'참고 범위':'관찰 항목'}</div></div></div><div class="tabs" role="tablist"><button role="tab" aria-selected="${detailTab==='feature'}" data-detail="feature" class="${detailTab==='feature'?'active':''}">특징</button><button role="tab" aria-selected="${detailTab==='tip'}" data-detail="tip" class="${detailTab==='tip'?'active':''}">${isHealth?'준비':'팁'}</button><button role="tab" aria-selected="${detailTab==='record'}" data-detail="record" class="${detailTab==='record'?'active':''}">기록</button></div><div id="detailBody"></div><a class="source-link" href="${i.src}" target="_blank" rel="noopener">${isHealth?'공식 일정':i.kind==='cdc'?'CDC 월령별 안내':'참고 자료'} 확인</a>`;if(detailTab==='feature')$('#detailBody').innerHTML=`<p>${i.text}</p>${productDetails(i)}${i.group==='motor'&&!i.kind?'<p class="note">연구에서 관찰된 분포의 범위로, 개인별 발달 마감일이 아닙니다.</p>':''}<div class="tip">${isHealth?'접종 수첩이나 지난 검진 결과를 준비하고 궁금한 점을 메모해 가세요.':i.tip}</div>`;else if(detailTab==='tip')$('#detailBody').innerHTML=`<p>${isHealth?'정확한 대상 기간과 이전 기록을 먼저 확인해 주세요. 예약한 날짜와 의료기관은 기록 메모에 남길 수 있어요.':i.tip}</p><div class="tip">${isHealth?'아래 확인 표시는 보호자의 개인 메모이며 공식 접종·검진 완료 증명은 아닙니다.':i.group==='supplies'?'현재 사용 제품의 라벨을 확인하고 변경한 날짜와 사용감을 기록하세요.':'잘하는지 시험하기보다 함께 즐기는 짧은 놀이로 만나 주세요.'}</div>`;else{const obs=state.observations[i.id];$('#detailBody').innerHTML=isHealth?`<p>${state.checks[i.id]?'일정을 확인했다고 기록했어요.':'아직 확인 기록이 없어요.'}</p>`:obs?`<p><strong>관찰했어요 · ${pretty(obs.date)}</strong></p><p style="white-space:pre-wrap">${escapeHTML(obs.note||'처음 발견한 모습을 남겼어요.')}</p>`:'<p>새로운 모습을 발견한 날을 기록해 보세요.</p>'}$('#detailBody').insertAdjacentHTML('beforeend',`<button class="primary ${isHealth?'':'yellow'}" id="recordSelected">${isHealth?(state.checks[i.id]?'확인 표시 취소':'일정 확인했어요'):(state.observations[i.id]?'기록 수정':i.group==='supplies'?'사용·교체 기록하기':'관찰 기록하기')}</button>`);$('#recordSelected').onclick=()=>{if(isHealth){toggleCheck(i.id);renderDetail()}else observationForm(i)};$$('[data-detail]').forEach(b=>b.onclick=()=>{detailTab=b.dataset.detail;renderDetail()})}
function renderBelow(){const m=selectedMonth;$('#checkTitle').textContent=m+'개월에 챙길 일';const items=events.filter(e=>e.point!=null?Math.abs(e.point-m)<=1:e.start<=m+1&&e.end>m);$('#currentChecks').innerHTML=(items.length?items.slice(0,3):[{id:'review'+m,title:'접종·검진 기록 살펴보기',text:'지난 기록과 다음 일정을 확인해 보세요.'}]).map(e=>`<label class="check"><input type="checkbox" data-check="${e.id}" ${state.checks[e.id]?'checked':''}><span><strong>${e.title}</strong><small>${e.start!=null||e.point!=null?rangeLabel(e):e.text}</small></span></label>`).join('');$$('#currentChecks [data-check]').forEach(b=>b.onchange=()=>toggleCheck(b.dataset.check));const tips=m<6?['눈을 맞추고 이야기해요','아기의 표정과 소리에 부드럽게 반응해 주세요. 일상에서 서로 얼굴을 바라보는 시간을 만들어 보세요.','작은 반응도 관찰 메모에 남겨 보세요.']:m<10?['까꿍, 여기 있었네!','얼굴을 가렸다 보여주며 까꿍 놀이를 해 보세요. 아기가 웃거나 소리 내면 함께 반응해 주세요.','낯선 사람 앞에서 머뭇거리거나 보호자를 찾는 모습을 보일 수 있어요.']:m<15?['숨긴 장난감 찾기','큰 장난감을 천 아래에 살짝 숨겨 보세요. 찾았을 때 “여기 있었네!” 하고 함께 기뻐해 주세요.','새로운 곳을 탐색할 때는 보호자가 가까이서 지켜봐 주세요.']:m<24?['인형에게 밥을 줘요','숟가락으로 인형에게 먹이는 시늉을 하며 번갈아 놀아 보세요. 짧고 쉬운 말로 행동을 설명해 주세요.','자기가 해 보고 싶은 마음을 존중하며 간단한 선택지를 주세요.']:m<36?['함께 색깔을 찾아요','그림책과 주변 물건에서 같은 색을 찾아보고, 두 단계의 짧은 부탁을 놀이로 해 보세요.','친구 옆에서 노는 것도 관계를 배우는 과정이에요.']:['오늘 이야기를 들려줘요','오늘 즐거웠던 일을 묻고 답을 기다려요. 익숙한 책의 다음 장면을 상상해 보세요.','글자를 읽는 시험보다 이야기와 역할 놀이를 즐겨요.'];$('#tipTitle').textContent=m+'개월 놀이 · '+tips[0];$('#monthlyTip').textContent=tips[1];$('#monthlyFeature').textContent=tips[2]}
function toggleCheck(id){state.checks[id]=!state.checks[id];if(!state.checks[id])delete state.checks[id];const ok=save();renderBoard();renderBelow();renderSchedule();if(ok)toast('확인 내역을 저장했어요')}
function openModal(title,html){$('#modalTitle').textContent=title;$('#modalContent').innerHTML=html;$('#modal').showModal()}
function closeModal(){$('#modal').close()}
function measurementForm(focus='height'){openModal('오늘의 성장 기록',`<form id="measureForm"><label class="field">측정한 날짜<input name="date" type="date" required min="${state.profile.birth}" max="${TODAY()}" value="${TODAY()}"></label><div class="form-grid"><label class="field">키 (cm)<input name="height" type="number" step="0.1" min="20" max="150" inputmode="decimal" placeholder="예: 74.5"></label><label class="field">몸무게 (kg)<input name="weight" type="number" step="0.01" min="0.5" max="50" inputmode="decimal" placeholder="예: 9.2"></label></div><label class="field">키 측정 자세<select name="posture"><option value="unknown">선택해 주세요</option><option value="lying">누워서 측정</option><option value="standing">서서 측정</option></select></label><p class="note">WHO 성별·연령별 기준의 추정 백분위입니다. 측정일 나이를 적용하며 월별 LMS 값을 보간합니다. 조산아 교정연령은 자동 적용하지 않아요. 백분위는 건강 점수가 아닙니다.</p><button class="primary yellow" type="submit">기록 저장</button></form>`);$('#measureForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),r={id:Date.now(),date:f.get('date'),posture:f.get('posture')};for(const k of ['height','weight'])r[k]=f.get(k)===''?null:Number(f.get(k));if(r.height===null&&r.weight===null){toast('측정값을 하나 이상 입력해 주세요');return}state.measurements.push(r);const ok=save();renderMetrics();renderRecords();closeModal();if(ok)toast('성장 기록을 저장했어요')};setTimeout(()=>$(`#measureForm [name="${focus}"]`).focus(),100)}
function observationForm(i){const o=state.observations[i.id]||{date:TODAY(),note:''};openModal('관찰 기록하기',`<p>${escapeHTML(i.title)}</p><form id="obsForm"><label class="field">관찰한 날짜<input type="date" name="date" min="${state.profile.birth}" max="${TODAY()}" value="${o.date}" required></label><label class="field">기억하고 싶은 순간<textarea name="note" maxlength="1200" placeholder="어떤 상황에서 어떤 모습을 보였나요?">${escapeHTML(o.note)}</textarea></label><button class="primary yellow">관찰했어요 · 저장</button>${state.observations[i.id]?'<button type="button" class="outline" id="removeObs">이 관찰 기록 삭제</button>':''}</form>`);$('#obsForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.observations[i.id]={date:f.get('date'),note:f.get('note').trim()};const ok=save();renderBoard();detailTab='record';renderDetail();renderRecords();closeModal();if(ok)toast('소중한 순간을 기록했어요')};if($('#removeObs'))$('#removeObs').onclick=()=>{delete state.observations[i.id];save();renderBoard();renderDetail();renderRecords();closeModal()}}
function renderRecords(){const list=[...state.measurements].sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id);$('#measurementList').innerHTML=list.length?list.map(r=>`<div class="logitem"><div class="content"><strong>${[['height','키','cm'],['weight','몸무게','kg']].filter(([k])=>r[k]!=null).map(([k,l,u])=>l+' '+r[k]+u+' ('+percentileLabel(r,k)+')').join(' · ')}</strong><small>${pretty(r.date)} · ${ageAt(state.profile.birth,r.date).months}개월</small></div><button class="delete" data-remove="${r.id}" aria-label="${r.date} 신체 기록 삭제">삭제</button></div>`).join(''):'<div class="empty">아직 측정 기록이 없어요.<br>첫 기록부터 성장 그래프가 시작됩니다.</div>';$$('[data-remove]').forEach(b=>b.onclick=()=>{openModal('기록을 삭제할까요?',`<p>선택한 신체 기록을 지웁니다.</p><button class="primary" id="confirmDelete">삭제</button>`);$('#confirmDelete').onclick=()=>{state.measurements=state.measurements.filter(x=>String(x.id)!==b.dataset.remove);save();renderMetrics();renderRecords();closeModal()}});const obs=Object.entries(state.observations).sort((a,b)=>b[1].date.localeCompare(a[1].date));$('#observationList').innerHTML=obs.length?obs.map(([id,o])=>`<div class="logitem"><div class="content"><strong>${escapeHTML(skills.find(x=>x.id===id)?.title||id)}</strong><small>${pretty(o.date)}</small><p>${escapeHTML(o.note)}</p></div><button class="smallbtn" data-editobs="${id}">수정</button></div>`).join(''):'<div class="empty">발달 구간표에서 항목을 눌러<br>관찰한 모습을 남겨 보세요.</div>';$$('[data-editobs]').forEach(b=>b.onclick=()=>observationForm(skills.find(i=>i.id===b.dataset.editobs)||{id:b.dataset.editobs,title:b.dataset.editobs}));renderChart()}
function renderChart(){const k=$('#chartMetric').value,rows=[...state.measurements].filter(r=>r[k]!=null).sort((a,b)=>a.date.localeCompare(b.date)||a.id-b.id);if(!rows.length){$('#growthChart').innerHTML='<div class="empty" style="border:0">선택한 항목의 기록을 추가하면<br>날짜별 변화를 볼 수 있어요.</div>';return}const vals=rows.map(r=>r[k]),min=Math.min(...vals),max=Math.max(...vals),span=max-min||1,t0=+parse(rows[0].date),t1=+parse(rows.at(-1).date),pts=rows.map(r=>[45+(t1===t0?0:(parse(r.date)-t0)/(t1-t0)*455),130-(r[k]-min)/span*90]);$('#growthChart').innerHTML=`<svg class="chart" viewBox="0 0 550 180" role="img" aria-label="기록한 측정값의 변화. 상세 값은 아래 신체 기록에서 확인할 수 있습니다."><path d="M45 30V145H515" fill="none" stroke="#dde2e6"/><text x="5" y="45" fill="#7b828a" font-size="12">${max}</text><text x="5" y="135" fill="#7b828a" font-size="12">${min}</text><polyline points="${pts.map(p=>p.join(',')).join(' ')}" fill="none" stroke="#d5ac21" stroke-width="3"/>${pts.map(([x,y],i)=>`<circle cx="${x}" cy="${y}" r="5" fill="#e3bb36"><title>${rows[i].date}: ${vals[i]}</title></circle>`).join('')}<text x="45" y="168" font-size="12" fill="#7b828a">${rows[0].date}</text><text x="510" y="168" text-anchor="end" font-size="12" fill="#7b828a">${rows.length>1?rows.at(-1).date:''}</text></svg>`}
function eventDate(e){if(e.dayStart)return iso(new Date(+parse(state.profile.birth)+e.dayStart*dayms))+' ~ '+iso(new Date(+parse(state.profile.birth)+e.dayEnd*dayms));const start=plusMonths(state.profile.birth,e.point??e.start);if(e.point!=null)return pretty(start)+' 무렵';return pretty(start)+'부터 · '+rangeLabel(e)}
function renderSchedule(){const a=current();const sorted=[...events].sort((a,b)=>(a.point??a.start)-(b.point??b.start));const list=sorted.filter(e=>scheduleFilter==='done'?!!state.checks[e.id]:scheduleFilter==='all'||(e.end??e.point+1)>a.months);$('#scheduleList').innerHTML=list.length?list.map(e=>{const now=(e.point??e.start)<=a.months&&(e.end??e.point+1)>a.months;return `<section class="card schedule-card"><span class="tag">${state.checks[e.id]?'확인 완료':now?'지금 확인':'참고 일정'} · ${e.type}</span><div class="top"><input aria-label="${e.title} 일정 확인" type="checkbox" data-eventcheck="${e.id}" ${state.checks[e.id]?'checked':''}><div><h3>${e.title}</h3><small>${eventDate(e)}</small><p style="margin:9px 0">${e.text}</p><a class="source-link" href="${e.src}" target="_blank" rel="noopener">공식 안내 보기</a></div></div></section>`}).join(''):'<div class="empty">해당하는 일정이 없어요.</div>';$$('[data-eventcheck]').forEach(b=>b.onchange=()=>toggleCheck(b.dataset.eventcheck))}
function showPage(page){$$('.page').forEach(e=>e.classList.toggle('hidden',e.id!=='page-'+page));$$('[data-page]').forEach(b=>{b.classList.toggle('active',b.dataset.page===page);b.setAttribute('aria-current',b.dataset.page===page?'page':'false')});if(page==='records')renderRecords();if(page==='schedule')renderSchedule();window.scrollTo({top:0,behavior:'smooth'})}
function loginInfo(){openModal('Google 로그인',`<p>정식 버전에서는 Google 계정으로 로그인해 아이의 기록을 이어서 볼 수 있어요.</p><button class="google-large" disabled><span class="g">G</span> Google로 계속하기</button><p class="note">현재는 로그인·온라인 저장이 연결되지 않은 HTML 버전입니다. 지금은 로그인 없이 이 브라우저에 기록할 수 있어요.</p><button class="primary yellow" id="localContinue">이 브라우저에서 계속하기</button>`);$('#localContinue').onclick=closeModal}
$('#login').onclick=loginInfo;$('#guideLogin').onclick=loginInfo;$('#closeModal').onclick=closeModal;$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=$('#modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal()}});
$('#editProfile').onclick=()=>{openModal('우리 아이 정보',`<form id="profileForm"><label class="field">이름<input name="name" value="${escapeHTML(state.profile.name)}" required maxlength="20"></label><label class="field">생년월일<input name="birth" type="date" value="${state.profile.birth}" min="2020-01-01" max="${TODAY()}" required></label><label class="field">성장도표 성별<select name="sex"><option value="boys" ${state.profile.sex!=='girls'?'selected':''}>남아</option><option value="girls" ${state.profile.sex==='girls'?'selected':''}>여아</option></select></label><p class="note">현재 아이의 정보를 수정합니다. 생일을 바꾸면 월령과 참고 일정을 다시 계산해요.</p><button class="primary yellow">저장</button></form>`);$('#profileForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),name=f.get('name').trim(),birth=f.get('birth');if(!name)return;const earliest=[...state.measurements.map(r=>r.date),...Object.values(state.observations).map(r=>r.date)].sort()[0];if(earliest&&birth>earliest){toast('기존 기록 날짜보다 늦은 생일은 저장할 수 없어요');return}state.profile={name,birth,sex:f.get('sex')};const ok=save();renderHeader();renderDetail();renderSchedule();goToday();closeModal();if(ok)toast('아이 정보를 저장했어요')}};
$('#todayBtn').onclick=goToday;$('#prev').onclick=()=>$('#board').scrollBy({left:-colWidth()*3,behavior:'smooth'});$('#next').onclick=()=>$('#board').scrollBy({left:colWidth()*3,behavior:'smooth'});$('#board').onscroll=updatePeriod;
$$('[data-unit]').forEach(b=>b.onclick=()=>{unit=b.dataset.unit;$$('[data-unit]').forEach(x=>x.classList.toggle('active',x===b));renderBoard()});$$('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$$('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderBoard()});$$('[data-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$$('[data-schedule]').forEach(b=>b.onclick=()=>{scheduleFilter=b.dataset.schedule;$$('[data-schedule]').forEach(x=>x.classList.toggle('active',x===b));renderSchedule()});$('#addMeasurement').onclick=()=>measurementForm();$('#chartMetric').onchange=renderChart;
$('#export').onclick=()=>{const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='yuha-growth-records-'+TODAY()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('기록 파일을 내려받습니다')};
$('#sources').innerHTML=[['WHO 운동 발달 구간',SRC.who,'앉기·서기·기기·걷기의 연구 관찰 범위'],['CDC 발달 이정표',SRC.cdc+'index.html','2~48개월 주요 관찰 항목과 놀이 안내'],['질병관리청 예방접종도우미',SRC.nip,'표준 예방접종 일정과 백신별 안내'],['보건복지부 영유아 건강검진',SRC.check,'월령별 검진 시기와 검진 항목'],['WHO 성장도표',SRC.growth,'성별·연령별 신체 성장 참고 자료']].map(([t,u,d])=>`<div class="source-card"><a href="${u}" target="_blank" rel="noopener">${t}</a><p>${d}</p></div>`).join('');
renderHeader();renderBoard();renderDetail();renderBelow();renderRecords();renderSchedule();requestAnimationFrame(()=>{$('#board').scrollLeft=Math.max(0,(selectedMonth-1)*colWidth());updatePeriod()});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'show_growth_month',description:'Navigate to a month in the baby growth roadmap. Does not modify records.',inputSchema:{type:'object',properties:{month:{type:'integer',minimum:0,maximum:48}},required:['month'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!Number.isInteger(input.month)||input.month<0||input.month>48)throw new Error('month must be an integer from 0 to 48');selectedMonth=input.month;showPage('roadmap');renderBoard();renderBelow();$('#board').scrollLeft=Math.max(0,(selectedMonth-1)*colWidth());return{month:selectedMonth}}})).catch(()=>{})}catch{}}

window.addEventListener('resize',updatePeriod);

function productDetails(i){let html='';if(i.weightNote){const latest=[...state.measurements].filter(r=>r.weight!=null).sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id)[0];html+=`<div class="tip">${latest?`최근 기록: ${latest.weight}kg · ${pretty(latest.date)}<br>구매 전 현재 체중과 제품 포장 기준을 확인해 주세요.`:'몸무게를 기록하면 최근 측정값을 여기서 함께 볼 수 있어요.'}</div>`}if(i.table)html+=`<table class="product-table"><caption>${escapeHTML(i.table.caption)}</caption><thead><tr>${i.table.headers.map(x=>`<th scope="col">${escapeHTML(x)}</th>`).join('')}</tr></thead><tbody>${i.table.rows.map(r=>`<tr>${r.map(x=>`<td>${escapeHTML(x)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;if(i.extraSources)html+=i.extraSources.map(([title,url])=>`<a class="source-link" href="${escapeHTML(url)}" target="_blank" rel="noopener">${escapeHTML(title)}</a>`).join('');return html}
