'use strict';
window.cloudAvailable=true;
const cloud={client:null,user:null,revision:0,dirty:false,busy:false,ready:false,conflict:false,generation:0};
function cloudKey(){return 'yuha-cloud-'+cloud.user.id}
function cloudMessage(s){document.querySelector('#storageNote').textContent=s}
function cacheCloud(){try{localStorage.setItem(cloudKey(),JSON.stringify({state,revision:cloud.revision,dirty:cloud.dirty}));return true}catch{toast('이 기기 임시 저장 실패 · 기록을 내려받아 주세요');return false}}
function cloudChanged(){cloud.dirty=true;cloud.generation++;cacheCloud();cloudMessage('온라인 저장 대기 중…');void syncCloud()}
async function syncCloud(){if(!cloud.user||!cloud.ready||cloud.busy||cloud.conflict)return;cloud.busy=true;const uid=cloud.user.id;try{while(cloud.dirty&&cloud.user?.id===uid){const generation=cloud.generation,payload=structuredClone(state),next=cloud.revision+1;let q=cloud.revision===0?cloud.client.from('yg_growth_records').insert({user_id:uid,state:payload,revision:1}):cloud.client.from('yg_growth_records').update({state:payload,revision:next,updated_at:new Date().toISOString()}).eq('user_id',uid).eq('revision',cloud.revision);const {data,error}=await q.select('revision').maybeSingle();if(cloud.user?.id!==uid)return;if(error){if(error.code==='23505'){cloud.conflict=true;cloudMessage('다른 기기의 새 기록이 있어요 · 로그인 메뉴에서 확인');return}throw error}if(!data){cloud.conflict=true;cloudMessage('다른 기기의 새 기록이 있어요 · 로그인 메뉴에서 확인');return}cloud.revision=data.revision;cloud.dirty=generation!==cloud.generation;cacheCloud()}cloudMessage('✓ Google 계정에 저장됨')}catch{cloudMessage('온라인 저장 실패 · 이 기기에 보관 중, 연결 후 다시 시도')}finally{cloud.busy=false}}
function validState(v){const date=s=>typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(+parse(s))&&iso(parse(s))===s;return !!(v&&v.version===1&&v.profile&&typeof v.profile.name==='string'&&v.profile.name.length<=40&&date(v.profile.birth)&&(!v.profile.sex||['boys','girls'].includes(v.profile.sex))&&Array.isArray(v.measurements)&&v.measurements.every(r=>r&&Number.isFinite(r.id)&&date(r.date)&&['height','weight'].every(k=>r[k]==null||(typeof r[k]==='number'&&Number.isFinite(r[k])&&r[k]>0)))&&v.observations&&typeof v.observations==='object'&&Object.entries(v.observations).every(([id,o])=>/^[a-zA-Z0-9_-]+$/.test(id)&&o&&date(o.date)&&typeof o.note==='string')&&v.checks&&typeof v.checks==='object'&&Object.entries(v.checks).every(([id,c])=>/^[a-zA-Z0-9_-]+$/.test(id)&&typeof c==='boolean'))}

function refreshAll(){renderHeader();renderBoard();renderDetail();renderBelow();renderRecords();renderSchedule();goToday()}
async function loadAccount(user){cloud.user=user;cloud.ready=false;cloud.conflict=false;cloud.dirty=false;cloud.revision=0;let cache;try{cache=JSON.parse(localStorage.getItem(cloudKey()))}catch{}state=validState(cache?.state)?cache.state:structuredClone(DEFAULT);refreshAll();$('#login').textContent='계정 · 저장';cloudMessage('계정 기록을 불러오는 중…');const {data,error}=await cloud.client.from('yg_growth_records').select('state,revision').eq('user_id',user.id).maybeSingle();if(cloud.user?.id!==user.id)return;if(error){cloudMessage('기록 연결 실패 · 계정 메뉴에서 다시 연결해 주세요');return}try{cache=JSON.parse(localStorage.getItem(cloudKey()))}catch{}cloud.ready=true;if(cache?.dirty){cloud.revision=cache.revision;cloud.dirty=true;if((data?.revision||0)!==cache.revision){cloud.conflict=true;cloudMessage('기기와 온라인 기록이 달라요 · 계정 메뉴에서 확인');return}await syncCloud()}else{state=validState(data?.state)?data.state:structuredClone(DEFAULT);cloud.revision=data?.revision||0;cacheCloud();refreshAll();cloudMessage(data?'✓ 계정 기록을 불러왔어요':'Google 로그인 완료 · 첫 기록을 기다려요')}}
async function googleSignIn(){if(location.protocol==='file:'){toast('Google 로그인은 배포된 사이트에서 이용해 주세요');return}const {error}=await cloud.client.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+location.pathname,queryParams:{prompt:'select_account'}}});if(error)toast('Google 연결 실패 · 잠시 뒤 다시 시도해 주세요')}
function cloudLogin(){if(!cloud.client){toast('로그인 연결을 준비 중이에요');return}if(!cloud.user){openModal('Google로 기록 이어 보기','<p>로그인하면 기기가 바뀌어도 같은 계정의 기록을 볼 수 있어요. 이 기기에서 작성한 기록은 로그인 후 선택해서 가져올 수 있습니다.</p><button id="doGoogle" class="google-large"><span class="g">G</span> Google로 계속하기</button><p class="note">아이 이름·생일·측정값·관찰 메모를 계정별로 저장합니다.</p>');$('#doGoogle').onclick=googleSignIn;return}openModal('계정과 저장',`<p>${escapeHTML(cloud.user.email||'Google 계정')}</p><p class="note">${cloud.dirty?'아직 온라인에 반영되지 않은 기록이 있어요.':'기록은 로그인 계정별로 분리되어 있어요.'}</p>${cloud.conflict?'<div class="cloud-conflict">다른 기기에서 기록이 바뀌었어요. 현재 기록을 내려받아 보관한 뒤 온라인 기록을 불러오세요.</div><button id="cloudDownload" class="outline">현재 기록 내려받기</button><button id="reloadCloud" class="primary yellow">온라인 기록으로 다시 불러오기</button>':'<button id="retryCloud" class="outline">저장·연결 다시 시도</button>'}<button id="importGuest" class="outline">이 기기 기록 가져오기</button><label class="field">이전 HTML 기록 파일 가져오기<input id="importFile" type="file" accept="application/json,.json"></label><button id="signOut" class="outline">로그아웃</button>`);if($('#cloudDownload'))$('#cloudDownload').onclick=()=>$('#export').click();if($('#reloadCloud'))$('#reloadCloud').onclick=()=>{openModal('온라인 기록을 불러올까요?','<p>현재 기기의 미전송 변경은 온라인 기록으로 교체됩니다. 필요한 기록은 먼저 내려받아 주세요.</p><button id="confirmReload" class="primary">불러오기</button>');$('#confirmReload').onclick=async()=>{try{localStorage.removeItem(cloudKey())}catch{}closeModal();await loadAccount(cloud.user)}};if($('#retryCloud'))$('#retryCloud').onclick=async()=>{closeModal();if(!cloud.ready)await loadAccount(cloud.user);else await syncCloud()};$('#importGuest').onclick=()=>{let guest;try{guest=JSON.parse(localStorage.getItem('yuha-growth-v1'))}catch{}offerImport(guest)};$('#importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>1000000){toast('1MB 이하 기록 파일을 선택해 주세요');return}try{offerImport(JSON.parse(await f.text()))}catch{toast('기록 파일을 읽을 수 없어요')}};$('#signOut').onclick=async()=>{if(cloud.busy){toast('저장이 끝난 뒤 다시 시도해 주세요');return}if(cloud.dirty){openModal('저장 대기 기록이 있어요','<p>먼저 기록을 내려받거나 연결을 재시도해 주세요.</p><button id="saveBeforeOut" class="outline">기록 내려받기</button><button id="forceOut" class="primary">이 기기에 남기고 로그아웃</button>');$('#saveBeforeOut').onclick=()=>$('#export').click();$('#forceOut').onclick=signOutCloud}else await signOutCloud()}}
function offerImport(v){if(!validState(v)){toast('가져올 수 있는 기록이 없어요');return}if(!cloud.ready||cloud.conflict){toast('먼저 온라인 연결과 기록 충돌을 해결해 주세요');return}openModal('계정으로 기록 가져오기',`<p>${escapeHTML(v.profile.name)} · 측정 ${v.measurements.length}건, 관찰 ${Object.keys(v.observations).length}건</p><p>현재 계정의 아이 정보와 기록을 가져온 내용으로 교체합니다. 기존 기록은 먼저 내려받아 보관하세요.</p><button id="backupImport" class="outline">현재 기록 내려받기</button><button id="confirmImport" class="primary yellow">이 내용으로 가져오기</button>`);$('#backupImport').onclick=()=>$('#export').click();$('#confirmImport').onclick=()=>{state=v;save();refreshAll();closeModal()}}
async function signOutCloud(){await cloud.client.auth.signOut({scope:'local'});cloud.user=null;cloud.ready=false;cloud.dirty=false;try{const v=JSON.parse(localStorage.getItem('yuha-growth-v1'));state=validState(v)?v:structuredClone(DEFAULT)}catch{state=structuredClone(DEFAULT)}refreshAll();$('#login').innerHTML='<span class="g">G</span> Google 로그인';cloudMessage('◌ 로그인 전 · 이 브라우저에 저장');closeModal()}
async function initCloud(){try{if(!window.Supabase||!window.YUHA_CONFIG)throw Error();cloud.client=Supabase.createClient(YUHA_CONFIG.supabaseUrl,YUHA_CONFIG.supabaseKey,{auth:{flowType:'pkce',persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'yuha-auth-v1'}});const {data,error}=await cloud.client.auth.getSession();if(error)throw error;if(data.session?.user)await loadAccount(data.session.user);cloud.client.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_IN'&&session?.user.id!==cloud.user?.id)setTimeout(()=>loadAccount(session.user),0);if(event==='SIGNED_OUT'&&cloud.user)setTimeout(()=>signOutCloud(),0)});if(new URLSearchParams(location.search).has('code'))history.replaceState(null,'',location.pathname);if(location.hash.includes('error'))toast('로그인에 실패했어요. 다시 시도해 주세요.')}catch{cloudMessage('Google 연결을 확인할 수 없어요 · 기기 기록은 이용 가능')}$('#login').onclick=cloudLogin;$('#guideLogin').onclick=cloudLogin}
window.addEventListener('online',()=>{if(cloud.user){if(cloud.ready)void syncCloud();else void loadAccount(cloud.user)}});window.addEventListener('beforeunload',e=>{if(cloud.user&&cloud.dirty){e.preventDefault();e.returnValue=''}});void initCloud();
